### ISSUE TITLE
API details could use code examples

### ISSUE THREAD

**Issue by BoCupp-Microsoft** [dlibby-/EditContext#27]
Here's my checklist of things we should show in code (basically every operation):

    * Enabling OS input services for an editable part of the document
    * "" two or more parts of the document
    * Specifying the mode of input to enable software keyboard specialization
    * Providing the text of the document to the OS input layer for context
    * Providing selection information to the OS input layer 
    * Providing position information to the OS input layer
    * Applying decorations over the API at the request of the OS input layer
    * Replacing the text of the document at the request of the OS input layer
    * Adjusting the selection of the document at the request of the OS input layer
    * Notifying the OS input layer that text has changed independent of its input
    * Resolving conflicts and requesting replay

**Comment by dlibby-** [comment]
I agree with all of these except for the last - don't think that is demonstrable in javascript code
