### ISSUE TITLE
Consider adding to the overview something about the value of stateful text services

### ISSUE THREAD

**Issue by BoCupp-Microsoft** [dlibby-/EditContext#3]
The reason "scraping of HTML" and "in order to derive the correct representation" are mentioned I don't think is clear unless you explain that we must communicate our DOM as text to a stateful text services OS feature in order to get benefits like suggestions.

**Comment by dlibby-** [comment]
Clarified the language here a bit. The statement was more about editor using contenteditable off-the-shelf, in which case, they don't have a clean representation of their model, but instead have to derive it from the DOM that contenteditable creates.
